name: Deploy Quartz

on:
  push:
    branches:
      - v4   # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Check npm version
        run: |
          v=$(npm --version)
          printf "npm version: %s\n" "$v"
          npx semver -r ">=10.9.2" "$v" || (echo "❌ npm too old" && exit 1)


      - name: Install dependencies
        run: npm ci

      - name: Check types and style
        run: npm run check

      - name: Test
        run: npm test

      - name: Build Quartz
        run: npx quartz build

      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.QUARTZ_HOST }}
          username: tim
          key: ${{ secrets.QUARTZ_SSH_KEY }}
          source: "public/*"
          target: "/home/tim/quartz/public"
          rm: true

      - name: Reload Nginx
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.QUARTZ_HOST }}
          username: tim
          key: ${{ secrets.QUARTZ_SSH_KEY }}
          script: |
            sudo systemctl reload nginx
